name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          IGNORED_REPOS: "Workshop-5-Car-Dealership, Hotel-Operations, Java"
          IGNORE_UNKNOWN_PROJECTS: "True"
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          
          
